=== Nickviera/assignment-1--databases--cs-365--fall-2024/xml/student.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (firstName, middleName?, lastName, preferredName?, studentID, email, phone, status, GPA, major, minor?, enrollmentStatus, advisor, initialEnrollment, graduationDate)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT middleName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT preferredName (#PCDATA)>
<!ELEMENT studentID (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT GPA (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT enrollmentStatus (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!ELEMENT initialEnrollment (#PCDATA)>
<!ELEMENT graduationDate (#PCDATA)>

=== Nickviera/assignment-1--databases--cs-365--fall-2024/xml/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "student.dtd">
<students>
  <student>
    <firstName>Gordon</firstName>
    <middleName>Matthew</middleName>
    <lastName>Sumner</lastName>
    <preferredName>Sting</preferredName>
    <studentID>1234567</studentID>
    <email>sting@thepolice.com</email>
    <phone>212.123.4567</phone>
    <status>first year</status>
    <GPA>4.0</GPA>
    <major>Music</major>
    <minor>English</minor>
    <enrollmentStatus>full-time</enrollmentStatus>
    <advisor>Andy Summers</advisor>
    <initialEnrollment>1969-08-25</initialEnrollment>
    <graduationDate>1973-05-01</graduationDate>
  </student>

  <student>
    <firstName>Kim</firstName>
    <middleName/>
    <lastName>Thayil</lastName>
    <studentID>4567890</studentID>
    <email>kim@soundgarden.com</email>
    <phone>206.123.4567</phone>
    <status>second year</status>
    <GPA>3.0</GPA>
    <major>Philosophy</major>
    <minor>Music</minor>
    <enrollmentStatus>full-time</enrollmentStatus>
    <advisor>Chris Cornell</advisor>
    <initialEnrollment>1978-08-25</initialEnrollment>
    <graduationDate>1982-05-01</graduationDate>
  </student>

  <student>
    <firstName>Saul</firstName>
    <middleName/>
    <lastName>Hudson</lastName>
    <preferredName>Slash</preferredName>
    <studentID>8302438</studentID>
    <email>slash@gnr.com</email>
    <phone>213.456.8392</phone>
    <status>fourth year</status>
    <GPA>2.0</GPA>
    <major>Music</major>
    <minor>Criminal Justice</minor>
    <enrollmentStatus>part-time</enrollmentStatus>
    <advisor>Axl Rose</advisor>
    <initialEnrollment>1983-08-25</initialEnrollment>
    <graduationDate>1987-05-01</graduationDate>
  </student>

  <student>
    <firstName>Emily</firstName>
    <middleName/>
    <lastName>Kokal</lastName>
    <studentID>2983928</studentID>
    <email>emily@warpaint.com</email>
    <phone>213.123.7654</phone>
    <status>third year</status>
    <GPA>3.8</GPA>
    <major>Political Science</major>
    <minor>Law</minor>
    <enrollmentStatus>full-time</enrollmentStatus>
    <advisor>Jenny Lee Lindberg</advisor>
    <initialEnrollment>1998-08-25</initialEnrollment>
    <graduationDate>2002-05-01</graduationDate>
  </student>
</students>
